// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.6.0 (commit 3c16edb3503eab8aad562e011d7fb452e051267d).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { ClientConnected } from "./client_connected_reducer.ts";
export { ClientConnected };
import { ClientDisconnected } from "./client_disconnected_reducer.ts";
export { ClientDisconnected };
import { ReducerGetCoinCommand } from "./reducer_get_coin_command_reducer.ts";
export { ReducerGetCoinCommand };
import { ReducerGetUserCommand } from "./reducer_get_user_command_reducer.ts";
export { ReducerGetUserCommand };
import { ReducerHelpCommand } from "./reducer_help_command_reducer.ts";
export { ReducerHelpCommand };
import { SendMessage } from "./send_message_reducer.ts";
export { SendMessage };
import { SetName } from "./set_name_reducer.ts";
export { SetName };

// Import and reexport all table handle types
import { ItemTableHandle } from "./item_table.ts";
export { ItemTableHandle };
import { MessageTableHandle } from "./message_table.ts";
export { MessageTableHandle };
import { ResponseTableHandle } from "./response_table.ts";
export { ResponseTableHandle };
import { UserTableHandle } from "./user_table.ts";
export { UserTableHandle };

// Import and reexport all types
import { ItemRow } from "./item_row_type.ts";
export { ItemRow };
import { MessageRow } from "./message_row_type.ts";
export { MessageRow };
import { ResponseRow } from "./response_row_type.ts";
export { ResponseRow };
import { UserRow } from "./user_row_type.ts";
export { UserRow };

const REMOTE_MODULE = {
  tables: {
    item: {
      tableName: "item" as const,
      rowType: ItemRow.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (ItemRow.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    message: {
      tableName: "message" as const,
      rowType: MessageRow.getTypeScriptAlgebraicType(),
    },
    response: {
      tableName: "response" as const,
      rowType: ResponseRow.getTypeScriptAlgebraicType(),
    },
    user: {
      tableName: "user" as const,
      rowType: UserRow.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
      primaryKeyInfo: {
        colName: "identity",
        colType: (UserRow.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    ClientConnected: {
      reducerName: "ClientConnected",
      argsType: ClientConnected.getTypeScriptAlgebraicType(),
    },
    ClientDisconnected: {
      reducerName: "ClientDisconnected",
      argsType: ClientDisconnected.getTypeScriptAlgebraicType(),
    },
    reducer_getCoinCommand: {
      reducerName: "reducer_getCoinCommand",
      argsType: ReducerGetCoinCommand.getTypeScriptAlgebraicType(),
    },
    reducer_getUserCommand: {
      reducerName: "reducer_getUserCommand",
      argsType: ReducerGetUserCommand.getTypeScriptAlgebraicType(),
    },
    reducer_helpCommand: {
      reducerName: "reducer_helpCommand",
      argsType: ReducerHelpCommand.getTypeScriptAlgebraicType(),
    },
    SendMessage: {
      reducerName: "SendMessage",
      argsType: SendMessage.getTypeScriptAlgebraicType(),
    },
    SetName: {
      reducerName: "SetName",
      argsType: SetName.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.6.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "ClientConnected", args: ClientConnected }
| { name: "ClientDisconnected", args: ClientDisconnected }
| { name: "ReducerGetCoinCommand", args: ReducerGetCoinCommand }
| { name: "ReducerGetUserCommand", args: ReducerGetUserCommand }
| { name: "ReducerHelpCommand", args: ReducerHelpCommand }
| { name: "SendMessage", args: SendMessage }
| { name: "SetName", args: SetName }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  onClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("ClientConnected", callback);
  }

  removeOnClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("ClientConnected", callback);
  }

  onClientDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("ClientDisconnected", callback);
  }

  removeOnClientDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("ClientDisconnected", callback);
  }

  reducerGetCoinCommand() {
    this.connection.callReducer("reducer_getCoinCommand", new Uint8Array(0), this.setCallReducerFlags.reducerGetCoinCommandFlags);
  }

  onReducerGetCoinCommand(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("reducer_getCoinCommand", callback);
  }

  removeOnReducerGetCoinCommand(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("reducer_getCoinCommand", callback);
  }

  reducerGetUserCommand(username: string) {
    const __args = { username };
    let __writer = new __BinaryWriter(1024);
    ReducerGetUserCommand.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("reducer_getUserCommand", __argsBuffer, this.setCallReducerFlags.reducerGetUserCommandFlags);
  }

  onReducerGetUserCommand(callback: (ctx: ReducerEventContext, username: string) => void) {
    this.connection.onReducer("reducer_getUserCommand", callback);
  }

  removeOnReducerGetUserCommand(callback: (ctx: ReducerEventContext, username: string) => void) {
    this.connection.offReducer("reducer_getUserCommand", callback);
  }

  reducerHelpCommand() {
    this.connection.callReducer("reducer_helpCommand", new Uint8Array(0), this.setCallReducerFlags.reducerHelpCommandFlags);
  }

  onReducerHelpCommand(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("reducer_helpCommand", callback);
  }

  removeOnReducerHelpCommand(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("reducer_helpCommand", callback);
  }

  sendMessage(text: string) {
    const __args = { text };
    let __writer = new __BinaryWriter(1024);
    SendMessage.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("SendMessage", __argsBuffer, this.setCallReducerFlags.sendMessageFlags);
  }

  onSendMessage(callback: (ctx: ReducerEventContext, text: string) => void) {
    this.connection.onReducer("SendMessage", callback);
  }

  removeOnSendMessage(callback: (ctx: ReducerEventContext, text: string) => void) {
    this.connection.offReducer("SendMessage", callback);
  }

  setName(name: string) {
    const __args = { name };
    let __writer = new __BinaryWriter(1024);
    SetName.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("SetName", __argsBuffer, this.setCallReducerFlags.setNameFlags);
  }

  onSetName(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.onReducer("SetName", callback);
  }

  removeOnSetName(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.offReducer("SetName", callback);
  }

}

export class SetReducerFlags {
  reducerGetCoinCommandFlags: __CallReducerFlags = 'FullUpdate';
  reducerGetCoinCommand(flags: __CallReducerFlags) {
    this.reducerGetCoinCommandFlags = flags;
  }

  reducerGetUserCommandFlags: __CallReducerFlags = 'FullUpdate';
  reducerGetUserCommand(flags: __CallReducerFlags) {
    this.reducerGetUserCommandFlags = flags;
  }

  reducerHelpCommandFlags: __CallReducerFlags = 'FullUpdate';
  reducerHelpCommand(flags: __CallReducerFlags) {
    this.reducerHelpCommandFlags = flags;
  }

  sendMessageFlags: __CallReducerFlags = 'FullUpdate';
  sendMessage(flags: __CallReducerFlags) {
    this.sendMessageFlags = flags;
  }

  setNameFlags: __CallReducerFlags = 'FullUpdate';
  setName(flags: __CallReducerFlags) {
    this.setNameFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get item(): ItemTableHandle<'item'> {
    // clientCache is a private property
    return new ItemTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<ItemRow>(REMOTE_MODULE.tables.item));
  }

  get message(): MessageTableHandle<'message'> {
    // clientCache is a private property
    return new MessageTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<MessageRow>(REMOTE_MODULE.tables.message));
  }

  get response(): ResponseTableHandle<'response'> {
    // clientCache is a private property
    return new ResponseTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<ResponseRow>(REMOTE_MODULE.tables.response));
  }

  get user(): UserTableHandle<'user'> {
    // clientCache is a private property
    return new UserTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<UserRow>(REMOTE_MODULE.tables.user));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
